# Generated by Django 3.2.5 on 2021-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.ImageField(max_length=10, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
        ),
    ]
